homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 10.8428143
  longitude: 106.7771262
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Ho_Chi_Minh
  # Customization file
  customize: !include customize.yaml
  # whitelist_external_dirs:
  # - '/tmp'    
# Show links to resources in log and frontend
# introduction:
lovelace:
  mode: yaml
system_health:
config:
geo_location:
zone: 
  - name: Home
    latitude: 10.8398976
    longitude: 106.7768017
    radius: 1500
    passive: true
  - name: Work
    latitude: 10.8101933
    longitude: 106.6943513
    radius: 1500
updater:
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: 1234
    pending_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0
# Enables support for tracking state changes over time
history:
shopping_list:
frontend:
  javascript_version: latest
logbook:
map:
input_number:
  slider1:
    name: Hour
    icon: mdi:timer
    initial: 5
    min: 0
    max: 23
    step: 1
    
  slider2:
    name: Minutes
    icon: mdi:timer
    initial: 00
    min: 0
    max: 59
    step: 5

  slider3:
    name: volume gateway
    icon: mdi:volume-plus
    initial: 10
    min: 10
    max: 100
    step: 10

  slider4:
    name: ringstone
    icon: mdi:music
    initial: 22
    min: 20
    max: 29
    step: 1

input_select:
  mode:
    options:
      - Tivi
      - Fan
      - Amply
      - AC
  che_do:
    options:
      - Media
      - Remote
      - Alarm
      - Contact
input_boolean:
  alarmweekday:
    name: Weekdays Only
    initial: off
    icon: mdi:calendar
  home:
    name: home
    icon: mdi:home
  remote:
    name: remote
    icon: mdi:remote
  system:
    name: system
    icon: mdi:information-outline
  camera:
    name: camera
    icon: mdi:weather-cloudy
  weather:
    name: weather
    icon: mdi:weather-cloudy
  music:
    icon: mdi:music-circle-outline
    name: music   
  living:
    name: Phòng Khách
  kitchen:
    name: Nhà Bếp
  bedroom:
    name: Phòng Ngủ
  gara: 
    name: Ga- ra
  tivi:
    name: tivi
  fan:
    name: fan
  amply:
    name: amply
  sctv:
    name: sctv
  alarm:
    name: alarm
  doit:
    name: doit
  people:
    name: people
  plant:
    name: plant
  other:
    name: other
  light: 
    name: Đèn
  sensor: 
    name: Cảm biến
sun:
 
speedtestdotnet:
  server_id: 9994
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload
sensor:
  - platform: template
    sensors:
      alarm_time:
        friendly_name: 'Time'
        value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.slider1") | int, states("input_number.slider2") | int) }}'

  - platform: moon
  # Weather prediction
  - platform: cpuspeed
  - platform: version
  - platform: uptime
    name: Time Online
    unit_of_measurement: hours
  
  - platform: systemmonitor
    resources:
      - type: memory_free
      - type: memory_use
      - type: processor_use
  - platform: darksky
    api_key: xxxx
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
      - precip_type
      - precip_intensity
      - precip_probability
      - precip_accumulation
      - temperature
      - wind_speed
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - daily_summary
      - apparent_temperature_low
      - precip_intensity_max
      - apparent_temperature_high
      - temperature_high
      - temperature_low
      
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
  # - platform: command_line
    # name: CPU Temperature
    # command: "cat /sys/class/thermal/thermal_zone0/temp"
    # unit_of_measurement: "°C"
    # value_template: '{{ value | multiply(0.001) | round(1) }}'
  - platform: template
    sensors:
      weathertoday:
        friendly_name: "Thời tiết hôm nay" 
        value_template: >-
          {% if is_state('sensor.dark_sky_icon', 'partly-cloudy-day') %}
            Ngày trời ít mây
          {% elif is_state('sensor.dark_sky_icon', 'clear-day') %}
            Ngày trời trong xanh
          {% elif is_state('sensor.dark_sky_icon', 'clear-night') %}
            Đêm trời đẹp
          {% elif is_state('sensor.dark_sky_icon', 'rain') %}
            Trời mưa
          {% elif is_state('sensor.dark_sky_icon', 'wind') %}
            Gió nhiều
          {% elif is_state('sensor.dark_sky_icon', 'cloudy') %}
            Trời nhiều mây
          {% elif is_state('sensor.dark_sky_icon', 'partly-cloudy-night') %}
            Đêm trời nhiều mây
          {% elif is_state('sensor.dark_sky_icon', 'fog') %}
            Sương mù
          {% elif is_state('sensor.dark_sky_nearest_storm_distance', 'unknown') %}
            Không có cơn bão nào
          {% else %}
            ...
          {% endif %}
  - platform: template
    sensors:
      sun_state:
        friendly_name: "Mặt trời"
        value_template: >-
          {% if is_state('sun.sun', 'above_horizon') %}
            Đã mọc
          {% else %}
            Đã lặn
          {% endif %}
  - platform: template
    sensors:
      moon_state:
        friendly_name: "Mặt trăng"
        value_template: >-
          {% if is_state('sensor.moon', 'full_moon') %}
            Trăng tròn
          {% else %}
            Trăng khuyết
          {% endif %}
weather:
  - platform: darksky
    api_key: xxxx
    mode: daily
cloud:
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
